QUOTE_LENGTH = 180

rsi_upper = 80
rsi_lower = 20

j_upper = 90
j_lower = 10

adxr_toohot = 50 #-1
adxr_hot = 45     #0
adxr_warm = 40   #1
adxr_best = 35   #2 
adxr_good = 30   #1
adxr_watch = 25  #0
adxr_warning =20 #-1
 

MACD_TYPE = "MACD_R"
MACD_POS_TYPE = "MACD_POS"
RSI_TYPE = "RSI"
J_TYPE = "KDJ"
ADX_TYPE = "ADX"
ADX_REC_TYPE = "ADX_R"
ADXR_TYPE = "ADXR"
ADXR_REC_TYPE = "ADXR_R"
RECOMMENDATION_TYPE = "REC"

STOCKLIST_CPH = "stocklist.txt"
CPHEXCHANGE = ".CO"
STOCKLIST_STO = "stocklist_sto.txt"
STOEXCHANGE = ".ST"
STOCKLIST_AMS = "stocklist_as.txt"
MYPF = "portfolio.txt"

BUYLIST = "today_recommendation_to_buy.txt"
SELLLIST = "today_recommendation_to_sell.txt"

HTML_TREND_REPORT_FILENAME = "TrendReport.html"
HTML_REPORT_FILENAME = "FullReport.html"
HTML_PORTOFOLIO_REPORT_FULLNAME = "PortfolioReport.html"
FTP_INFO_FILE = "ftpinfo.yaml"

COLORCODE_REC_STRONGBUY = """BGCOLOR=#006600"""  #DARK GREEN
COLORCODE_REC_BUY = """BGCOLOR=#006699"""  #DARK BLUE 
COLORCODE_REC_MAYBUY =  """BGCOLOR=#FFffff""" # WHITE
COLORCODE_REC_WATCH = """BGCOLOR=ffff00"""  #DARK YELLOW
COLORCODE_REC_MAYSELL = """BGCOLOR=#CC6600"""  #DARK ORANGE
COLORCODE_REC_SELL = """BGCOLOR=#cc0000"""  #DARK RED

COLORCODE_OUTSTANDINGSIGN = """BGCOLOR=#99ff66"""  #LIGHT GREEN
COLORCODE_GOODSIGN = """BGCOLOR=#66ffff"""  #LIGHT Blue
COLORCODE_NEUTURALSIGN = """BGCOLOR=#FFffff"""  #WHITE
COLORCODE_WATCHSIGN = """BGCOLOR=#ffff66"""  #LIGHT YELLOW
COLORCODE_WARNINGSIGN = """BGCOLOR=#cc99ff"""  #LIGHT PURPLE
COLORCODE_QUITSIGN = """BGCOLOR=#ff3399"""  #LIGHT RED



 
