rsi_upper = 80
rsi_lower = 20

j_upper = 90
j_lower = 10

MACD_TYPE = "MACD_R"
MACD_POS_TYPE = "MACD_POS"
RSI_TYPE = "RSI"
J_TYPE = "KDJ"
RECOMMENDATION_TYPE = "REC"

HTML_REPORT_FILENAME = "FullReport.html"

COLORCODE_REC_STRONGBUY = """BGCOLOR=#006600"""  #DARK GREEN
COLORCODE_REC_BUY = """BGCOLOR=#006699"""  #DARK BLUE 
COLORCODE_REC_MAYBUY =  """BGCOLOR=#FFffff""" # WHITE
COLORCODE_REC_WATCH = """BGCOLOR=ffff00"""  #DARK YELLOW
COLORCODE_REC_MAYSELL = """BGCOLOR=#CC6600"""  #DARK ORANGE
COLORCODE_REC_SELL = """BGCOLOR=#cc0000"""  #DARK READ

COLORCODE_OUTSTANDINGSIGN = """BGCOLOR=#99ff66"""  #LIGHT GREEN
COLORCODE_GOODSIGN = """BGCOLOR=#66ffff"""  #LIGHT GREEN
COLORCODE_NEUTURALSIGN = """BGCOLOR=#FFffff"""  #WHITE
COLORCODE_WATCHSIGN = """BGCOLOR=#ffff66"""  #LIGHT YELLOW
COLORCODE_WARNINGSIGN = """BGCOLOR=#cc99ff"""  #LIGHT PURPLE
COLORCODE_QUITSIGN = """BGCOLOR=#ff3399"""  #LIGHT READ



 
